# Generated by Django 5.0.1 on 2024-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
