# Generated by Django 5.0.1 on 2024-01-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_room_timer_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='timer_minutes',
        ),
    ]
