# Generated by Django 5.0.1 on 2024-01-29 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_room_timer_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='pending_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
