# Generated by Django 5.0.1 on 2024-01-30 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_room_join_requests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="leave_requests",
            field=models.ManyToManyField(
                blank=True, related_name="leave_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
