# Generated by Django 5.0.1 on 2024-01-31 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_room_leave_requests"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="leave_requests",
        ),
    ]
